### ISSUE TITLE
Basic usage without an LLM key?

### ISSUE THREAD

**Issue by gsamaras** [ngruver/llmtime#24]
I was wondering if I could quickly use your model without an LLM key (e.g. OpenAI key)?

**Comment by ngruver** [comment]
You can try running a LLaMA or mistral model locally, as shown in demo.py

**Comment by gsamaras** [comment]
Yes exactly, that is what I was trying in a Kaggle Haggle notebook, but it was asking for openai and Mistral keys. Can you provide an example?

I am only interested in feeding the air passenger dataset to LLMtime and get predictions, just for a basic demo

**Comment by zaizou** [comment]
@gsamaras 
You just need to comment the lines here 
![Code_1o9Y2gzX26](https://github.com/ngruver/llmtime/assets/8124554/2a1e0f71-2b57-415b-b45a-fdf8b36e787d)

or you create a dummy OPENAI_API_KEY env variable

**Comment by gsamaras** [comment]
@zaizou thank you for your suggestions. Unfortunately they don't work, since it asks for an openai key, as you can see on this Kaggle [notebook](https://www.kaggle.com/code/georgiossamaras/llm-time-demo-notebook), in which you are welcome to play around.

**Comment by zaizou** [comment]
Just comment the models that you don't want to use in the model_predict_fns variable
![Code_6VwxjaavpY](https://github.com/ngruver/llmtime/assets/8124554/680db3c1-8251-4ea2-bd35-a6c74a196f78)

**Comment by gsamaras** [comment]
@zaizou apologies, I had done that but didn't mention it. When I did this, it would ask for a Mistral Key. If I provide a dummy mistral key, it will say unauthorized. If I create a real Mistral key, it seems it is a pay-as-you-go service.

See the new version in my [notebook](https://www.kaggle.com/code/georgiossamaras/llm-time-demo-notebook).
