### ISSUE TITLE
ImportError: cannot import name 'load_dataset' from 'datasets' (unknown location) from monash.py

### ISSUE THREAD

**Issue by chenghaoliu89** [ngruver/llmtime#4]
Can you also provide the monash datasets you used to reproduce the results?

**Comment by shikaiqiu** [comment]
Hi, `datasets` is the Hugging Face datasets library and should have been installed by [running `sh install.sh` ](https://github.com/ngruver/llmtime/blob/main/install.sh). Let me if you still have issues.
