### ISSUE TITLE
Missing LLaMa from experiments

### ISSUE THREAD

**Issue by MohammadHossein-Bahari** [ngruver/llmtime#5]
Hello,

Thanks for sharing the code for the exciting work. 
It seems that LLaMa is not in the experiments you shared.
In Monash, llama is initialized with empty hyperparameters and is never called. Similarly, it is not initialized in other experiments. 

Since it is an open-source model, it is easier to work with that. Can you share the code for that please?  

Thanks!

**Comment by shikaiqiu** [comment]
Hi,

Thanks for bringing this up! We will add full support for LLaMA by next week. 

Best,
Shikai

**Comment by shikaiqiu** [comment]
Hi,

We have updated the hyperparameters for LLaMA. You should be able to run it now. 

Best,
Shikai
